#!/bin/sh

LLVM_CONFIG_BIN=$(find /usr/bin -name 'llvm-config*' -not -name '*.h' | head -1)

if [ "$1" = "--libs" ]; then
    "$LLVM_CONFIG_BIN" "$@" "--system-libs" "--link-static"
else
    "$LLVM_CONFIG_BIN" "$@"
fi
